package com.berrybyte.RPT.export;

import com.berrybyte.RPT.model.InfoPharmaTurnoverReport;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.kernel.pdf.canvas.draw.SolidLine;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.borders.Border;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.LineSeparator;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.HorizontalAlignment;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;

import java.awt.Desktop;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class InfoPharmaTurnoverPdfService {

    public Path generateInfoPharmaTurnoverPdf(InfoPharmaTurnoverReport report) throws Exception {
        if (report == null) {
            throw new IllegalArgumentException("InfoPharma turnover report is required.");
        }

        Path reportDirectory = resolveReportDirectory();
        Files.createDirectories(reportDirectory);

        String baseFileName = "infopharma-turnover-" + System.currentTimeMillis();
        Path pdfPath = reportDirectory.resolve(baseFileName + ".pdf");

        try {
            writePdf(pdfPath, report);
            return pdfPath;
        } catch (IOException firstFailure) {
            Path fallbackPath = reportDirectory.resolve(baseFileName + "-fallback.pdf");
            writePdf(fallbackPath, report);
            return fallbackPath;
        }
    }

    public void openInfoPharmaTurnoverPdf(Path pdfPath) throws Exception {
        if (pdfPath == null || !Files.exists(pdfPath)) {
            throw new IOException("InfoPharma turnover PDF could not be found.");
        }
        if (!Desktop.isDesktopSupported()) {
            throw new IOException("PDF saved to " + pdfPath.toAbsolutePath() + ", but this machine cannot open it automatically.");
        }
        Desktop desktop = Desktop.getDesktop();
        if (!desktop.isSupported(Desktop.Action.OPEN)) {
            throw new IOException("PDF saved to " + pdfPath.toAbsolutePath() + ", but no open action is available.");
        }

        desktop.open(pdfPath.toFile());
    }

    private void writePdf(Path pdfPath, InfoPharmaTurnoverReport report) throws Exception {
        try (Document document = new Document(new PdfDocument(new PdfWriter(pdfPath.toString())))) {
            document.setMargins(36, 36, 36, 36);

            addHeader(document, report);
            addSummarySection(document, report);

            document.add(new Paragraph("Generated by IPOS-SA")
                    .setFontSize(9)
                    .setFontColor(ColorConstants.GRAY)
                    .setMarginTop(20));
        }
    }

    private void addHeader(Document document, InfoPharmaTurnoverReport report) {
        document.add(new Paragraph(report.getTitle()).setFontSize(24));
        document.add(new Paragraph("Period: " + report.getStartDate() + " to " + report.getEndDate()).setFontSize(10));
        document.add(new Paragraph("Generated: " + report.getGeneratedAt()).setFontSize(10));
        document.add(new Paragraph("\n"));
        document.add(new LineSeparator(new SolidLine()));
        document.add(new Paragraph("\n"));
    }

    private void addSummarySection(Document document, InfoPharmaTurnoverReport report) {
        Table summaryTable = new Table(UnitValue.createPercentArray(new float[]{2f, 1f}))
                .setWidth(UnitValue.createPercentValue(50))
                .setHorizontalAlignment(HorizontalAlignment.RIGHT);

        addSummaryRow(summaryTable, "Total Invoices", String.valueOf(report.getTotalInvoices()));
        addSummaryRow(summaryTable, "Total Invoiced", formatCurrency(report.getTotalInvoicedAmount().doubleValue()));
        addSummaryRow(summaryTable, "Total Paid", formatCurrency(report.getTotalPaidAmount().doubleValue()));
        addSummaryRow(summaryTable, "Outstanding Total", formatCurrency(report.getTotalOutstandingAmount().doubleValue()));
        addSummaryRow(summaryTable, "Paid Invoices", String.valueOf(report.getPaidInvoiceCount()));
        addSummaryRow(summaryTable, "Unpaid Invoices", String.valueOf(report.getUnpaidInvoiceCount()));
        addSummaryRow(summaryTable, "Partial Invoices", String.valueOf(report.getPartialInvoiceCount()));

        document.add(summaryTable);
    }

    private void addSummaryRow(Table table, String label, String value) {
        table.addCell(new Cell()
                .add(new Paragraph(label))
                .setPadding(8)
                .setBorder(Border.NO_BORDER));
        table.addCell(new Cell()
                .add(new Paragraph(value))
                .setTextAlignment(TextAlignment.RIGHT)
                .setPadding(8)
                .setBorder(Border.NO_BORDER));
    }

    private String formatCurrency(double value) {
        return String.format("GBP %.2f", value);
    }

    private Path resolveReportDirectory() {
        Path userHome = Paths.get(System.getProperty("user.home"));
        Path documentsDir = userHome.resolve("Documents");
        Path baseDir = Files.isDirectory(documentsDir) ? documentsDir : userHome;
        return baseDir.resolve("IPOS-SA").resolve("Reports");
    }
}