package com.berrybyte.RPT.export;

import com.berrybyte.RPT.model.InvoiceListingReport;
import com.berrybyte.RPT.model.InvoiceListingRow;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.kernel.pdf.canvas.draw.SolidLine;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.borders.Border;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.LineSeparator;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.HorizontalAlignment;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;

import java.awt.Desktop;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * Represents invoice listing pdf service.
 */
public class InvoiceListingPdfService {
/**
 * Executes the generate invoice listing pdf workflow.
 * This method coordinates the main operation for this action.
 *
 * @param report report
 * @return result value
 * @throws Exception when the operation fails
 */

    public Path generateInvoiceListingPdf(InvoiceListingReport report) throws Exception {
        if (report == null) {
            throw new IllegalArgumentException("Invoice listing report is required.");
        }

        Path reportDirectory = resolveReportDirectory();
        Files.createDirectories(reportDirectory);

        String baseFileName = "invoice-listing-" + System.currentTimeMillis();
        Path pdfPath = reportDirectory.resolve(baseFileName + ".pdf");

        try {
            writePdf(pdfPath, report);
            return pdfPath;
        } catch (IOException firstFailure) {
            Path fallbackPath = reportDirectory.resolve(baseFileName + "-fallback.pdf");
            writePdf(fallbackPath, report);
            return fallbackPath;
        }
    }
/**
 * Executes the open invoice listing pdf workflow.
 * This method coordinates the main operation for this action.
 *
 * @param pdfPath pdf path
 * @throws Exception when the operation fails
 */

    public void openInvoiceListingPdf(Path pdfPath) throws Exception {
        if (pdfPath == null || !Files.exists(pdfPath)) {
            throw new IOException("Invoice listing PDF could not be found.");
        }
        if (!Desktop.isDesktopSupported()) {
            throw new IOException("Invoice listing PDF saved to " + pdfPath.toAbsolutePath() + ", but this machine cannot open it automatically.");
        }
        Desktop desktop = Desktop.getDesktop();
        if (!desktop.isSupported(Desktop.Action.OPEN)) {
            throw new IOException("Invoice listing PDF saved to " + pdfPath.toAbsolutePath() + ", but no open action is available.");
        }

        desktop.open(pdfPath.toFile());
    }
/**
 * Performs write pdf.
 * This method coordinates the main operation for this action.
 *
 * @param pdfPath pdf path
 * @param report report
 * @throws Exception when the operation fails
 */

    private void writePdf(Path pdfPath, InvoiceListingReport report) throws Exception {
        try (Document document = new Document(new PdfDocument(new PdfWriter(pdfPath.toString())))) {
            document.setMargins(36, 36, 36, 36);

            addHeader(document, report);
            addItemsSection(document, report);
            addSummarySection(document, report);

            document.add(new Paragraph("Generated by IPOS-SA")
                    .setFontSize(9)
                    .setFontColor(ColorConstants.GRAY)
                    .setMarginTop(20));
        }
    }
/**
 * Performs add header.
 *
 * @param document document
 * @param report report
 */

    private void addHeader(Document document, InvoiceListingReport report) {
        document.add(new Paragraph(report.getTitle()).setFontSize(24));
        document.add(new Paragraph("Merchant ID: " + report.getMerchantId()).setFontSize(10));
        document.add(new Paragraph("Period: " + report.getStartDate() + " to " + report.getEndDate()).setFontSize(10));
        document.add(new Paragraph("Generated: " + report.getGeneratedAt()).setFontSize(10));
        document.add(new Paragraph("\n"));
        document.add(new LineSeparator(new SolidLine()));
        document.add(new Paragraph("\n"));
    }
/**
 * Performs add items section.
 *
 * @param document document
 * @param report report
 */

    private void addItemsSection(Document document, InvoiceListingReport report) {
        document.add(new Paragraph("Invoices").setFontSize(14).setMarginBottom(10));

        Table table = new Table(UnitValue.createPercentArray(new float[]{1.2f, 1.2f, 1.2f, 1.5f, 1.5f, 1.4f, 1.4f, 1.5f, 1.4f}))
                .useAllAvailableWidth();

        addHeaderCell(table, "Invoice ID");
        addHeaderCell(table, "Order ID");
        addHeaderCell(table, "Merchant");
        addHeaderCell(table, "Invoice Date");
        addHeaderCell(table, "Due Date");
        addHeaderCell(table, "Total");
        addHeaderCell(table, "Paid");
        addHeaderCell(table, "Outstanding");
        addHeaderCell(table, "Status");

        for (InvoiceListingRow row : report.getRows()) {
            table.addCell(bodyCell(String.valueOf(row.getInvoiceId())));
            table.addCell(bodyCell(String.valueOf(row.getOrderId())));
            table.addCell(bodyCell(String.valueOf(row.getMerchantId())));
            table.addCell(bodyCell(String.valueOf(row.getInvoiceDate())));
            table.addCell(bodyCell(String.valueOf(row.getDueDate())));
            table.addCell(bodyCell(formatCurrency(row.getTotalAmount().doubleValue())).setTextAlignment(TextAlignment.RIGHT));
            table.addCell(bodyCell(formatCurrency(row.getAmountPaid().doubleValue())).setTextAlignment(TextAlignment.RIGHT));
            table.addCell(bodyCell(formatCurrency(row.getOutstandingBalance().doubleValue())).setTextAlignment(TextAlignment.RIGHT));
            table.addCell(bodyCell(nonBlank(row.getPaymentStatus())));
        }

        document.add(table);
        document.add(new Paragraph("\n"));
    }
/**
 * Performs add summary section.
 *
 * @param document document
 * @param report report
 */

    private void addSummarySection(Document document, InvoiceListingReport report) {
        Table summaryTable = new Table(UnitValue.createPercentArray(new float[]{2f, 1f}))
                .setWidth(UnitValue.createPercentValue(45))
                .setHorizontalAlignment(HorizontalAlignment.RIGHT);

        addSummaryRow(summaryTable, "Total Invoices", String.valueOf(report.getTotalInvoices()));
        addSummaryRow(summaryTable, "Total Invoiced", formatCurrency(report.getTotalInvoicedAmount().doubleValue()));
        addSummaryRow(summaryTable, "Outstanding Total", formatCurrency(report.getTotalOutstandingAmount().doubleValue()));

        document.add(summaryTable);
    }
/**
 * Performs add header cell.
 *
 * @param table table
 * @param text text
 */

    private void addHeaderCell(Table table, String text) {
        table.addHeaderCell(new Cell()
                .add(new Paragraph(text).setFontColor(ColorConstants.WHITE))
                .setBackgroundColor(ColorConstants.DARK_GRAY)
                .setBorder(Border.NO_BORDER)
                .setPadding(8));
    }
/**
 * Performs body cell.
 *
 * @param text text
 * @return result value
 */

    private Cell bodyCell(String text) {
        return new Cell()
                .add(new Paragraph(text).setFontSize(10))
                .setPadding(8);
    }
/**
 * Performs add summary row.
 * This method coordinates the main operation for this action.
 *
 * @param table table
 * @param label label
 * @param value value
 */

    private void addSummaryRow(Table table, String label, String value) {
        table.addCell(new Cell()
                .add(new Paragraph(label))
                .setPadding(8));
        table.addCell(new Cell()
                .add(new Paragraph(value))
                .setTextAlignment(TextAlignment.RIGHT)
                .setPadding(8));
    }
/**
 * Performs format currency.
 *
 * @param value value
 * @return result value
 */

    private String formatCurrency(double value) {
        return String.format("GBP %.2f", value);
    }
/**
 * Performs non blank.
 *
 * @param value value
 * @return result value
 */

    private String nonBlank(String value) {
        return value == null || value.isBlank() ? "N/A" : value;
    }
/**
 * Performs resolve report directory.
 *
 * @return result value
 */

    private Path resolveReportDirectory() {
        Path userHome = Paths.get(System.getProperty("user.home"));
        Path documentsDir = userHome.resolve("Documents");
        Path baseDir = Files.isDirectory(documentsDir) ? documentsDir : userHome;
        return baseDir.resolve("IPOS-SA").resolve("Reports");
    }
}
