package com.berrybyte.RPT.export;

import com.berrybyte.RPT.model.OverdueBalanceReport;
import com.berrybyte.RPT.model.OverdueBalanceRow;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.kernel.pdf.canvas.draw.SolidLine;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.borders.Border;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.LineSeparator;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.UnitValue;

import java.awt.Desktop;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * Represents overdue balance pdf service.
 */
public class OverdueBalancePdfService {
/**
 * Executes the generate overdue balance pdf workflow.
 * This method coordinates the main operation for this action.
 *
 * @param report report
 * @return result value
 * @throws Exception when the operation fails
 */

    public Path generateOverdueBalancePdf(OverdueBalanceReport report) throws Exception {
        if (report == null) {
            throw new IllegalArgumentException("Overdue balance report is required.");
        }

        Path reportDirectory = resolveReportDirectory();
        Files.createDirectories(reportDirectory);

        String fileName = "overdue-balance-" + System.currentTimeMillis() + ".pdf";
        Path pdfPath = reportDirectory.resolve(fileName);

        try (Document document = new Document(new PdfDocument(new PdfWriter(pdfPath.toString())))) {
            document.setMargins(36, 36, 36, 36);

            document.add(new Paragraph(report.getTitle()).setFontSize(24));
            document.add(new Paragraph("Generated: " + report.getGeneratedAt()).setFontSize(10));

            if (report.getMerchantId() == null) {
                document.add(new Paragraph("Scope: All overdue merchant accounts").setFontSize(10));
            } else {
                document.add(new Paragraph("Scope: " + report.getMerchantName()).setFontSize(10));
            }

            document.add(new Paragraph("Total overdue accounts: " + report.getTotalAccounts()).setFontSize(10));
            document.add(new Paragraph("Total overdue amount: GBP " + formatMoney(report.getTotalOverdueAmount())).setFontSize(10));
            document.add(new Paragraph("\n"));
            document.add(new LineSeparator(new SolidLine()));
            document.add(new Paragraph("\n"));

            Table table = new Table(UnitValue.createPercentArray(new float[]{1.0f, 2.2f, 1.8f, 1.2f, 1.4f, 1.6f, 1.2f}))
                    .useAllAvailableWidth();

            addHeaderCell(table, "Merchant ID");
            addHeaderCell(table, "Company");
            addHeaderCell(table, "IPOS Account");
            addHeaderCell(table, "Status");
            addHeaderCell(table, "Oldest Due");
            addHeaderCell(table, "Overdue Amount");
            addHeaderCell(table, "Invoices");

            for (OverdueBalanceRow row : report.getRows()) {
                addBodyCell(table, String.valueOf(row.getMerchantId()));
                addBodyCell(table, row.getCompanyName());
                addBodyCell(table, row.getIposAccountNumber());
                addBodyCell(table, row.getAccountStatus());
                addBodyCell(table, row.getOldestDueDate().toString());
                addBodyCell(table, "GBP " + formatMoney(row.getTotalOverdueAmount()));
                addBodyCell(table, String.valueOf(row.getOverdueInvoiceCount()));
            }

            document.add(table);

            document.add(new Paragraph("\nGenerated by IPOS-SA")
                    .setFontSize(9)
                    .setFontColor(ColorConstants.GRAY));
        }

        return pdfPath;
    }
/**
 * Executes the open overdue balance pdf workflow.
 * This method coordinates the main operation for this action.
 *
 * @param pdfPath pdf path
 * @throws Exception when the operation fails
 */

    public void openOverdueBalancePdf(Path pdfPath) throws Exception {
        if (pdfPath == null || !Files.exists(pdfPath)) {
            throw new IOException("Overdue balance PDF could not be found.");
        }

        if (!Desktop.isDesktopSupported()) {
            throw new IOException("Desktop open is not supported on this machine.");
        }

        Desktop desktop = Desktop.getDesktop();

        if (!desktop.isSupported(Desktop.Action.OPEN)) {
            throw new IOException("Open action is not supported on this machine.");
        }

        desktop.open(pdfPath.toFile());
    }
/**
 * Performs add header cell.
 *
 * @param table table
 * @param text text
 */

    private void addHeaderCell(Table table, String text) {
        table.addHeaderCell(new Cell()
                .add(new Paragraph(text))
                .setBorder(Border.NO_BORDER)
                .setFontSize(10));
    }
/**
 * Performs add body cell.
 *
 * @param table table
 * @param text text
 */

    private void addBodyCell(Table table, String text) {
        table.addCell(new Cell()
                .add(new Paragraph(text == null ? "" : text))
                .setBorder(Border.NO_BORDER)
                .setFontSize(9));
    }
/**
 * Performs format money.
 *
 * @param value value
 * @return result value
 */

    private String formatMoney(java.math.BigDecimal value) {
        return value == null ? "0.00" : String.format("%.2f", value);
    }
/**
 * Performs resolve report directory.
 *
 * @return result value
 */

    private Path resolveReportDirectory() {
        Path userHome = Paths.get(System.getProperty("user.home"));
        Path documentsDir = userHome.resolve("Documents");
        Path baseDir = Files.isDirectory(documentsDir) ? documentsDir : userHome;
        return baseDir.resolve("IPOS-SA").resolve("Reports");
    }
}
