package com.berrybyte.RPT.controllers;

import com.berrybyte.RPT.email.ReportEmailService;
import com.berrybyte.RPT.email.ReportEmailServiceImpl;
import com.berrybyte.RPT.export.InvoiceListingPdfService;
import com.berrybyte.RPT.model.InvoiceListingReport;
import com.berrybyte.RPT.model.InvoiceListingRow;
import com.berrybyte.RPT.repository.ReportRepositoryImpl;
import com.berrybyte.RPT.services.ReportService;
import com.berrybyte.RPT.services.ReportServiceImpl;
import javafx.collections.FXCollections;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.stage.Stage;

import java.nio.file.Path;
import java.time.LocalDate;

public class InvoicesAgainstMerchantController {

    private final ReportService reportService = new ReportServiceImpl(new ReportRepositoryImpl());

    private String merchantSearch;
    private LocalDate afterDate;
    private LocalDate beforeDate;
    private InvoiceListingReport currentReport;
    private final InvoiceListingPdfService invoiceListingPdfService = new InvoiceListingPdfService();
    private static final String DEMO_RECIPIENT_EMAIL = "ipos_commercial@yahoo.com";
    private final ReportEmailService reportEmailService = new ReportEmailServiceImpl();

    @FXML
    private Label filterSummaryLabel;

    @FXML
    private Label messageLabel;

    @FXML
    private TableView<InvoiceListingRow> invoiceTable;

    @FXML
    private TableColumn<InvoiceListingRow, Integer> invoiceIdColumn;

    @FXML
    private TableColumn<InvoiceListingRow, Integer> orderIdColumn;

    @FXML
    private TableColumn<InvoiceListingRow, Integer> merchantIdColumn;

    @FXML
    private TableColumn<InvoiceListingRow, LocalDate> invoiceDateColumn;

    @FXML
    private TableColumn<InvoiceListingRow, LocalDate> dueDateColumn;

    @FXML
    private TableColumn<InvoiceListingRow, Number> totalAmountColumn;

    @FXML
    private TableColumn<InvoiceListingRow, Number> outstandingColumn;

    @FXML
    private Button refreshButton;

    @FXML
    private Button exportPdfButton;

    @FXML
    private Button sendEmailButton;

    @FXML
    private Button backButton;

    @FXML
    public void initialize() {
        invoiceIdColumn.setCellValueFactory(new PropertyValueFactory<>("invoiceId"));
        orderIdColumn.setCellValueFactory(new PropertyValueFactory<>("orderId"));
        merchantIdColumn.setCellValueFactory(new PropertyValueFactory<>("merchantId"));
        invoiceDateColumn.setCellValueFactory(new PropertyValueFactory<>("invoiceDate"));
        dueDateColumn.setCellValueFactory(new PropertyValueFactory<>("dueDate"));
        totalAmountColumn.setCellValueFactory(new PropertyValueFactory<>("totalAmount"));
        outstandingColumn.setCellValueFactory(new PropertyValueFactory<>("outstandingBalance"));

        updateFilterSummary();
    }

    public void setFilters(String merchantSearch, LocalDate afterDate, LocalDate beforeDate) {
        this.merchantSearch = merchantSearch == null ? "" : merchantSearch.trim();
        this.afterDate = afterDate;
        this.beforeDate = beforeDate;
        updateFilterSummary();
        loadReport();
    }

    @FXML
    private void handleRefresh() {
        loadReport();
    }

    @FXML
    private void handleExportPdf() {
        try {
            if (currentReport == null) {
                messageLabel.setText("No report loaded.");
                return;
            }

            Path pdfPath = invoiceListingPdfService.generateInvoiceListingPdf(currentReport);
            messageLabel.setText("PDF saved to: " + pdfPath.toAbsolutePath());
        } catch (Exception e) {
            e.printStackTrace();
            messageLabel.setText("Unable to export PDF.");
        }
    }

    @FXML
    private void handleSendEmail() {
        try {
            if (currentReport == null) {
                messageLabel.setText("No report loaded.");
                return;
            }

            Path pdfPath = invoiceListingPdfService.generateInvoiceListingPdf(currentReport);

            String subject = "Invoice Listing Report";
            String body = "Please find attached the invoice listing report generated by IPOS-SA for demo purposes.";

            reportEmailService.sendReportEmail(DEMO_RECIPIENT_EMAIL, subject, body, pdfPath);

            messageLabel.setText("Email sent to: " + DEMO_RECIPIENT_EMAIL);
        } catch (Exception e) {
            e.printStackTrace();
            messageLabel.setText("Unable to send email.");
        }
    }

    @FXML
    private void handleBack() {
        try {
            Parent root = FXMLLoader.load(getClass().getResource("/RPT/reportsMenu.fxml"));
            Stage stage = (Stage) backButton.getScene().getWindow();
            stage.setScene(new Scene(root));
            stage.setTitle("Reports");
            stage.show();
        } catch (Exception e) {
            e.printStackTrace();
            messageLabel.setText("Unable to go back.");
        }
    }

    private void loadReport() {
        try {
            Integer merchantId = parseMerchantId(merchantSearch);

            LocalDate startDate = afterDate != null ? afterDate : LocalDate.of(2000, 1, 1);
            LocalDate endDate = beforeDate != null ? beforeDate : LocalDate.now();

            currentReport = reportService.generateInvoiceListing(merchantId, startDate, endDate);
            invoiceTable.setItems(FXCollections.observableArrayList(currentReport.getRows()));
            messageLabel.setText("Loaded " + currentReport.getRows().size() + " invoice(s).");
        } catch (Exception e) {
            e.printStackTrace();
            invoiceTable.setItems(FXCollections.observableArrayList());
            messageLabel.setText("Unable to load invoice report.");
        }
    }

    private void updateFilterSummary() {
        String merchantText = (merchantSearch == null || merchantSearch.isBlank()) ? "Any merchant" : merchantSearch;
        String afterText = afterDate == null ? "Any" : afterDate.toString();
        String beforeText = beforeDate == null ? "Any" : beforeDate.toString();

        filterSummaryLabel.setText("Merchant: " + merchantText + " | After: " + afterText + " | Before: " + beforeText);
    }

    private Integer parseMerchantId(String text) {
        if (text == null || text.isBlank()) {
            return null;
        }

        try {
            return Integer.parseInt(text.trim());
        } catch (NumberFormatException e) {
            return null;
        }
    }
}