package com.berrybyte.RPT.controllers;

import com.berrybyte.RPT.email.ReportEmailService;
import com.berrybyte.RPT.email.ReportEmailServiceImpl;
import com.berrybyte.RPT.export.InvoiceListingPdfService;
import com.berrybyte.RPT.model.InvoiceListingReport;
import com.berrybyte.RPT.model.InvoiceListingRow;
import com.berrybyte.RPT.repository.ReportRepositoryImpl;
import com.berrybyte.RPT.services.ReportService;
import com.berrybyte.RPT.services.ReportServiceImpl;
import com.berrybyte.common.SceneSwitcher;
import javafx.collections.FXCollections;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;

import java.nio.file.Path;
import java.time.LocalDate;

public class InvoicesAgainstMerchantController extends ReportProfileMenuController {

    private static final String DEMO_RECIPIENT_EMAIL = "ipos_commercial@yahoo.com";

    private final ReportService reportService = new ReportServiceImpl(new ReportRepositoryImpl());
    private final InvoiceListingPdfService invoiceListingPdfService = new InvoiceListingPdfService();
    private final ReportEmailService reportEmailService = new ReportEmailServiceImpl();

    private Integer merchantId;
    private String merchantName;
    private LocalDate afterDate;
    private LocalDate beforeDate;
    private InvoiceListingReport currentReport;

    @FXML
    private Label filterSummaryLabel;

    @FXML
    private Label messageLabel;

    @FXML
    private TableView<InvoiceListingRow> invoiceTable;

    @FXML
    private TableColumn<InvoiceListingRow, Integer> invoiceIdColumn;

    @FXML
    private TableColumn<InvoiceListingRow, Integer> orderIdColumn;

    @FXML
    private TableColumn<InvoiceListingRow, Integer> merchantIdColumn;

    @FXML
    private TableColumn<InvoiceListingRow, LocalDate> invoiceDateColumn;

    @FXML
    private TableColumn<InvoiceListingRow, LocalDate> dueDateColumn;

    @FXML
    private TableColumn<InvoiceListingRow, Number> totalAmountColumn;

    @FXML
    private TableColumn<InvoiceListingRow, Number> outstandingColumn;

    @FXML
    private Button refreshButton;

    @FXML
    private Button exportPdfButton;

    @FXML
    private Button sendEmailButton;

    @FXML
    private Button backButton;

    @FXML
    public void initialize() {
        initializeProfileMenu();
        invoiceIdColumn.setCellValueFactory(new PropertyValueFactory<>("invoiceId"));
        orderIdColumn.setCellValueFactory(new PropertyValueFactory<>("orderId"));
        merchantIdColumn.setCellValueFactory(new PropertyValueFactory<>("merchantId"));
        invoiceDateColumn.setCellValueFactory(new PropertyValueFactory<>("invoiceDate"));
        dueDateColumn.setCellValueFactory(new PropertyValueFactory<>("dueDate"));
        totalAmountColumn.setCellValueFactory(new PropertyValueFactory<>("totalAmount"));
        outstandingColumn.setCellValueFactory(new PropertyValueFactory<>("outstandingBalance"));
        bindColumnWidths();

        updateFilterSummary();
    }

    public void setFilters(Integer merchantId, String merchantName, LocalDate afterDate, LocalDate beforeDate) {
        this.merchantId = merchantId;
        this.merchantName = merchantName == null ? "" : merchantName.trim();
        this.afterDate = afterDate;
        this.beforeDate = beforeDate;
        updateFilterSummary();
        loadReport();
    }

    @FXML
    private void handleRefresh() {
        loadReport();
    }

    @FXML
    private void handleExportPdf() {
        try {
            if (currentReport == null) {
                messageLabel.setText("No report loaded.");
                return;
            }

            Path pdfPath = invoiceListingPdfService.generateInvoiceListingPdf(currentReport);
            if (pdfPath == null || !java.nio.file.Files.exists(pdfPath)) {
                messageLabel.setText("PDF export failed.");
                return;
            }
            invoiceListingPdfService.openInvoiceListingPdf(pdfPath);
            messageLabel.setText("PDF opened: " + pdfPath.toAbsolutePath());
        } catch (Exception e) {
            e.printStackTrace();
            messageLabel.setText("Unable to export PDF.");
        }
    }

    @FXML
    private void handleSendEmail() {
        try {
            if (currentReport == null) {
                messageLabel.setText("No report loaded.");
                return;
            }

            Path pdfPath = invoiceListingPdfService.generateInvoiceListingPdf(currentReport);

            String subject = "Invoice Listing Report";
            String body = "Please find attached the invoice listing report generated by IPOS-SA for demo purposes.";

            reportEmailService.sendReportEmail(DEMO_RECIPIENT_EMAIL, subject, body, pdfPath);

            messageLabel.setText("Email sent to: " + DEMO_RECIPIENT_EMAIL);
        } catch (Exception e) {
            e.printStackTrace();
            messageLabel.setText("Unable to send email.");
        }
    }

    @FXML
    private void handleBack(ActionEvent event) {
        try {
            SceneSwitcher.switchScene(event, "/RPT/reportsMenu.fxml", "Reports");
        } catch (Exception e) {
            e.printStackTrace();
            messageLabel.setText("Unable to go back.");
        }
    }

    private void loadReport() {
        try {
            if (merchantId == null) {
                invoiceTable.setItems(FXCollections.observableArrayList());
                messageLabel.setText("Select a merchant from the reports menu.");
                return;
            }

            LocalDate startDate = afterDate != null ? afterDate : LocalDate.of(2000, 1, 1);
            LocalDate endDate = beforeDate != null ? beforeDate : LocalDate.now();

            currentReport = reportService.generateInvoiceListing(merchantId, startDate, endDate);
            invoiceTable.setItems(FXCollections.observableArrayList(currentReport.getRows()));
            messageLabel.setText("Loaded " + currentReport.getRows().size() + " invoice(s).");
        } catch (Exception e) {
            e.printStackTrace();
            invoiceTable.setItems(FXCollections.observableArrayList());
            messageLabel.setText("Unable to load invoice report.");
        }
    }

    private void updateFilterSummary() {
        String merchantText = (merchantName == null || merchantName.isBlank()) ? "Merchant required" : merchantName;
        String afterText = afterDate == null ? "Any" : afterDate.toString();
        String beforeText = beforeDate == null ? "Any" : beforeDate.toString();

        filterSummaryLabel.setText("Merchant: " + merchantText + " | After: " + afterText + " | Before: " + beforeText);
    }

    private void bindColumnWidths() {
        invoiceIdColumn.prefWidthProperty().bind(invoiceTable.widthProperty().multiply(0.10625));
        orderIdColumn.prefWidthProperty().bind(invoiceTable.widthProperty().multiply(0.09375));
        merchantIdColumn.prefWidthProperty().bind(invoiceTable.widthProperty().multiply(0.23125));
        invoiceDateColumn.prefWidthProperty().bind(invoiceTable.widthProperty().multiply(0.11875));
        dueDateColumn.prefWidthProperty().bind(invoiceTable.widthProperty().multiply(0.13375));
        totalAmountColumn.prefWidthProperty().bind(invoiceTable.widthProperty().multiply(0.1425));
        outstandingColumn.prefWidthProperty().bind(invoiceTable.widthProperty().multiply(0.17375));
    }
}
