package com.berrybyte.RPT.controllers;

import com.berrybyte.RPT.email.ReportEmailService;
import com.berrybyte.RPT.email.ReportEmailServiceImpl;
import com.berrybyte.RPT.export.MerchantActivityPdfService;
import com.berrybyte.RPT.model.MerchantActivityItemRow;
import com.berrybyte.RPT.model.MerchantActivityOrderSection;
import com.berrybyte.RPT.model.MerchantActivityReport;
import com.berrybyte.RPT.repository.ReportRepositoryImpl;
import com.berrybyte.RPT.services.ReportService;
import com.berrybyte.RPT.services.ReportServiceImpl;
import com.berrybyte.common.SceneSwitcher;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TextArea;

import java.nio.file.Path;
import java.time.LocalDate;

public class MerchantActivityReportController extends ReportProfileMenuController {

    private static final String DEMO_RECIPIENT_EMAIL = "ipos_commercial@yahoo.com";

    private final ReportService reportService = new ReportServiceImpl(new ReportRepositoryImpl());
    private final MerchantActivityPdfService merchantActivityPdfService = new MerchantActivityPdfService();
    private final ReportEmailService reportEmailService = new ReportEmailServiceImpl();

    private Integer merchantId;
    private String merchantName;
    private LocalDate afterDate;
    private LocalDate beforeDate;
    private MerchantActivityReport currentReport;

    @FXML
    private Label filterSummaryLabel;

    @FXML
    private Label messageLabel;

    @FXML
    private Label merchantHeaderLabel;

    @FXML
    private TextArea activityTextArea;

    @FXML
    private Button refreshButton;

    @FXML
    private Button exportPdfButton;

    @FXML
    private Button sendEmailButton;

    @FXML
    private Button backButton;

    @FXML
    public void initialize() {
        initializeProfileMenu();
        updateFilterSummary();
    }

    public void setFilters(Integer merchantId, String merchantName, LocalDate afterDate, LocalDate beforeDate) {
        this.merchantId = merchantId;
        this.merchantName = merchantName == null ? "" : merchantName.trim();
        this.afterDate = afterDate;
        this.beforeDate = beforeDate;
        updateFilterSummary();
        loadReport();
    }

    @FXML
    private void handleRefresh() {
        loadReport();
    }

    @FXML
    private void handleExportPdf() {
        try {
            if (currentReport == null) {
                messageLabel.setText("No report loaded.");
                return;
            }

            Path pdfPath = merchantActivityPdfService.generateMerchantActivityPdf(currentReport);
            if (pdfPath == null || !java.nio.file.Files.exists(pdfPath)) {
                messageLabel.setText("PDF export failed.");
                return;
            }
            merchantActivityPdfService.openMerchantActivityPdf(pdfPath);
            messageLabel.setText("PDF opened: " + pdfPath.toAbsolutePath());
        } catch (Exception e) {
            e.printStackTrace();
            messageLabel.setText("Unable to export PDF.");
        }
    }

    @FXML
    private void handleSendEmail() {
        try {
            if (currentReport == null) {
                messageLabel.setText("No report loaded.");
                return;
            }

            Path pdfPath = merchantActivityPdfService.generateMerchantActivityPdf(currentReport);

            String subject = "Merchant Activity Report";
            String body = "Please find attached the merchant activity report generated by IPOS-SA for demo purposes.";

            reportEmailService.sendReportEmail(DEMO_RECIPIENT_EMAIL, subject, body, pdfPath);

            messageLabel.setText("Email sent to: " + DEMO_RECIPIENT_EMAIL);
        } catch (Exception e) {
            e.printStackTrace();
            messageLabel.setText("Unable to send email.");
        }
    }

    @FXML
    private void handleBack(ActionEvent event) {
        try {
            SceneSwitcher.switchScene(event, "/RPT/reportsMenu.fxml", "Reports");
        } catch (Exception e) {
            e.printStackTrace();
            messageLabel.setText("Unable to go back.");
        }
    }

    private void loadReport() {
        try {
            if (merchantId == null) {
                merchantHeaderLabel.setText("Merchant details will appear here");
                activityTextArea.clear();
                messageLabel.setText("Select a merchant from the reports menu.");
                return;
            }

            LocalDate startDate = afterDate != null ? afterDate : LocalDate.of(2000, 1, 1);
            LocalDate endDate = beforeDate != null ? beforeDate : LocalDate.now();

            currentReport = reportService.generateMerchantActivityReport(merchantId, startDate, endDate);

            merchantHeaderLabel.setText(
                    currentReport.getCompanyName() +
                            " | Account: " + currentReport.getIposAccountNumber() +
                            " | Orders: " + currentReport.getTotalOrders()
            );

            activityTextArea.setText(buildActivityText(currentReport));
            messageLabel.setText("Loaded merchant activity report.");
        } catch (Exception e) {
            e.printStackTrace();
            merchantHeaderLabel.setText("Merchant details will appear here");
            activityTextArea.clear();
            messageLabel.setText("Unable to load merchant activity report.");
        }
    }

    private String buildActivityText(MerchantActivityReport report) {
        StringBuilder builder = new StringBuilder();

        builder.append("Merchant ID: ").append(report.getMerchantId()).append("\n");
        builder.append("Company: ").append(report.getCompanyName()).append("\n");
        builder.append("IPOS Account: ").append(report.getIposAccountNumber()).append("\n");
        builder.append("Address: ").append(report.getAddress()).append("\n");
        builder.append("Period: ").append(report.getStartDate()).append(" to ").append(report.getEndDate()).append("\n");
        builder.append("Total Orders: ").append(report.getTotalOrders()).append("\n");
        builder.append("Total Value: ").append(report.getTotalOrderValue()).append("\n\n");

        for (MerchantActivityOrderSection order : report.getOrders()) {
            builder.append("Order ").append(order.getOrderId())
                    .append(" | Date: ").append(order.getOrderDate())
                    .append(" | Total: ").append(order.getOrderTotal())
                    .append(" | Payment: ").append(order.getPaymentStatus())
                    .append(" | Outstanding: ").append(order.getOutstandingBalance())
                    .append("\n");

            for (MerchantActivityItemRow item : order.getItems()) {
                builder.append("   - Item ").append(item.getItemId())
                        .append(" | ").append(item.getDescription())
                        .append(" | Qty: ").append(item.getQuantity())
                        .append(" | Unit Cost: ").append(item.getUnitCost())
                        .append(" | Line Total: ").append(item.getLineTotal())
                        .append("\n");
            }

            builder.append("\n");
        }

        return builder.toString();
    }

    private void updateFilterSummary() {
        String merchantText = (merchantName == null || merchantName.isBlank()) ? "Merchant required" : merchantName;
        String afterText = afterDate == null ? "Any" : afterDate.toString();
        String beforeText = beforeDate == null ? "Any" : beforeDate.toString();

        filterSummaryLabel.setText("Merchant: " + merchantText + " | After: " + afterText + " | Before: " + beforeText);
    }
}
