package com.berrybyte.ORD.services;

import com.berrybyte.ORD.helpers.InvoiceDetails;
import com.berrybyte.ORD.helpers.InvoiceLine;
import com.itextpdf.kernel.colors.ColorConstants;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.kernel.pdf.canvas.draw.SolidLine;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.borders.Border;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.LineSeparator;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.element.Text;
import com.itextpdf.layout.properties.HorizontalAlignment;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.UnitValue;

import java.awt.Desktop;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class InvoicePdfService {

    public Path generateInvoicePdf(InvoiceDetails invoice) throws Exception {
        if (invoice == null) {
            throw new IllegalArgumentException("Invoice details are required.");
        }

        Path invoiceDirectory = resolveInvoiceDirectory();
        Files.createDirectories(invoiceDirectory);

        String baseFileName = String.format("invoice-%d-order-%d", invoice.getInvoiceId(), invoice.getOrderId());
        Path pdfPath = invoiceDirectory.resolve(baseFileName + ".pdf");

        try {
            writePdf(pdfPath, invoice);
            return pdfPath;
        } catch (IOException firstFailure) {
            Path fallbackPath = invoiceDirectory.resolve(baseFileName + "-" + System.currentTimeMillis() + ".pdf");
            writePdf(fallbackPath, invoice);
            return fallbackPath;
        }
    }

    public void openInvoicePdf(Path pdfPath) throws Exception {
        if (pdfPath == null || !Files.exists(pdfPath)) {
            throw new IOException("Invoice PDF could not be found.");
        }
        if (!Desktop.isDesktopSupported()) {
            throw new IOException("Invoice PDF saved to " + pdfPath.toAbsolutePath() + ", but this machine cannot open it automatically.");
        }
        Desktop desktop = Desktop.getDesktop();
        if (!desktop.isSupported(Desktop.Action.OPEN)) {
            throw new IOException("Invoice PDF saved to " + pdfPath.toAbsolutePath() + ", but no open action is available.");
        }

        desktop.open(pdfPath.toFile());
    }

    private void writePdf(Path pdfPath, InvoiceDetails invoice) throws Exception {
        try (Document document = new Document(new PdfDocument(new PdfWriter(pdfPath.toString())))) {
            document.setMargins(36, 36, 36, 36);

            addHeader(document, invoice);
            addMerchantSection(document, invoice);
            addItemsSection(document, invoice);
            addSummarySection(document, invoice);

            document.add(new Paragraph("Generated by IPOS-SA")
                    .setFontSize(9)
                    .setFontColor(ColorConstants.GRAY)
                    .setMarginTop(20));
        }
    }

    private void addHeader(Document document, InvoiceDetails invoice) {
        Table headerTable = new Table(UnitValue.createPercentArray(new float[]{3f, 2f})).useAllAvailableWidth();

        headerTable.addCell(borderlessCell(new Paragraph("INVOICE")
                .setFontSize(24)));

        Paragraph metaParagraph = new Paragraph()
                .add(labelValue("Invoice No", String.valueOf(invoice.getInvoiceId())))
                .add("\n")
                .add(labelValue("Order ID", String.valueOf(invoice.getOrderId())))
                .add("\n")
                .add(labelValue("Invoice Date", invoice.getInvoiceDate()))
                .add("\n")
                .add(labelValue("Due Date", invoice.getDueDate()));

        headerTable.addCell(borderlessCell(metaParagraph).setTextAlignment(TextAlignment.RIGHT));

        document.add(headerTable);
        document.add(new Paragraph("\n"));
        document.add(new LineSeparator(new SolidLine()));
        document.add(new Paragraph("\n"));
    }

    private void addMerchantSection(Document document, InvoiceDetails invoice) {
        Table infoTable = new Table(UnitValue.createPercentArray(new float[]{1f, 1f}))
                .useAllAvailableWidth();

        Paragraph merchantParagraph = new Paragraph()
                .add("Merchant Information\n")
                .add(nonBlank(invoice.getCompanyName()) + "\n")
                .add(nonBlank(invoice.getMerchantName()) + "\n")
                .add(nonBlank(invoice.getAddress()) + "\n")
                .add(nonBlank(invoice.getEmail()) + "\n")
                .add(nonBlank(invoice.getPhoneNumber()));

        Paragraph accountParagraph = new Paragraph()
                .add("Account Information\n")
                .add(labelValue("IPOS Account", nonBlank(invoice.getIposAccountNumber())))
                .add("\n")
                .add(labelValue("Merchant ID", String.valueOf(invoice.getMerchantId())))
                .add("\n")
                .add(labelValue("Payment Status", nonBlank(invoice.getPaymentStatus())));

        infoTable.addCell(borderlessCell(merchantParagraph));
        infoTable.addCell(borderlessCell(accountParagraph));

        document.add(infoTable);
        document.add(new Paragraph("\n"));
    }

    private void addItemsSection(Document document, InvoiceDetails invoice) {
        document.add(new Paragraph("Invoice Items").setFontSize(14).setMarginBottom(10));

        Table itemsTable = new Table(UnitValue.createPercentArray(new float[]{1.1f, 3.2f, 1.8f, 1.4f, 1.5f, 1.0f, 1.6f})).useAllAvailableWidth();

        addHeaderCell(itemsTable, "Item");
        addHeaderCell(itemsTable, "Description");
        addHeaderCell(itemsTable, "Package");
        addHeaderCell(itemsTable, "Units/Pack");
        addHeaderCell(itemsTable, "Unit Cost");
        addHeaderCell(itemsTable, "Qty");
        addHeaderCell(itemsTable, "Line Total");

        for (InvoiceLine item : invoice.getItems()) {
            itemsTable.addCell(bodyCell(String.valueOf(item.getItemId())));
            itemsTable.addCell(bodyCell(nonBlank(item.getDescription())));
            itemsTable.addCell(bodyCell(nonBlank(item.getPackageType())));
            itemsTable.addCell(bodyCell(String.valueOf(item.getUnitsInPacks())).setTextAlignment(TextAlignment.RIGHT));
            itemsTable.addCell(bodyCell(formatCurrency(item.getPacksCost())).setTextAlignment(TextAlignment.RIGHT));
            itemsTable.addCell(bodyCell(String.valueOf(item.getQuantity())).setTextAlignment(TextAlignment.RIGHT));
            itemsTable.addCell(bodyCell(formatCurrency(item.getLineTotal())).setTextAlignment(TextAlignment.RIGHT));
        }

        document.add(itemsTable);
        document.add(new Paragraph("\n"));
    }

    private void addSummarySection(Document document, InvoiceDetails invoice) {
        Table summaryTable = new Table(UnitValue.createPercentArray(new float[]{2f, 1f})).setWidth(UnitValue.createPercentValue(45)).setHorizontalAlignment(HorizontalAlignment.RIGHT);

        addSummaryRow(summaryTable, "Total Amount", formatCurrency(invoice.getTotalAmount()));
        addSummaryRow(summaryTable, "Amount Paid", formatCurrency(invoice.getAmountPaid()));
        addSummaryRow(summaryTable, "Outstanding Balance", formatCurrency(invoice.getOutstandingBalance()));
        addSummaryRow(summaryTable, "Payment Status", nonBlank(invoice.getPaymentStatus()));
        addSummaryRow(summaryTable, "Due Date", nonBlank(invoice.getDueDate()));

        document.add(summaryTable);
    }

    private void addHeaderCell(Table table, String text) {
        table.addHeaderCell(new Cell()
                .add(new Paragraph(text).setFontColor(ColorConstants.WHITE))
                .setBackgroundColor(ColorConstants.DARK_GRAY)
                .setBorder(Border.NO_BORDER)
                .setPadding(8));
    }

    private Cell bodyCell(String text) {
        return new Cell()
                .add(new Paragraph(text).setFontSize(10))
                .setPadding(8);
    }

    private void addSummaryRow(Table table, String label, String value) {
        table.addCell(new Cell()
                .add(new Paragraph(label))
                .setPadding(8));
        table.addCell(new Cell()
                .add(new Paragraph(value))
                .setTextAlignment(TextAlignment.RIGHT)
                .setPadding(8));
    }

    private Cell borderlessCell(Paragraph paragraph) {
        return new Cell()
                .add(paragraph)
                .setBorder(Border.NO_BORDER);
    }

    private Text labelValue(String label, String value) {
        return new Text(label + ": " + value);
    }

    private String formatCurrency(double value) {
        return String.format("GBP %.2f", value);
    }

    private String nonBlank(String value) {
        return value == null || value.isBlank() ? "N/A" : value;
    }

    private Path resolveInvoiceDirectory() {
        Path userHome = Paths.get(System.getProperty("user.home"));
        Path documentsDir = userHome.resolve("Documents");
        Path baseDir = Files.isDirectory(documentsDir) ? documentsDir : userHome;
        return baseDir.resolve("IPOS-SA").resolve("Invoices");
    }
}
